### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by kotinash** [GreenFrogMCBE/GreenFrogMCBE#335]
- [ ] Fully switch to snake case
- [ ] Better event emitter
- [ ] Update creative content packet
